# Generated by Django 4.2.6 on 2023-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursova_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='description',
            field=models.TextField(),
        ),
    ]
