# Generated by Django 4.2.6 on 2023-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursova_page', '0003_offers_offer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('offer_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
