# Generated by Django 4.2.6 on 2023-12-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kursova_page', '0004_destinations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='offer_image',
            new_name='dest_image',
        ),
    ]
