# Generated by Django 4.2.6 on 2023-12-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursova_page', '0008_alter_offers_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
